export const ADMIN_TABS = [
  { id: "reports", label: "Журнал" },
  { id: "keys", label: "API Keys" },
  { id: "operators", label: "Операторы" },
  { id: "captchas", label: "Капчи" },
  { id: "ai", label: "ИИ" },
  { id: "invoices", label: "Счета" },
  { id: "prepaid", label: "Предоплата" },
  { id: "expenses", label: "Расходы" },
  { id: "payouts", label: "Выплаты" },
  { id: "users", label: "Пользователи" },
  { id: "testbench", label: "Тесты и бенчмарк" },
  { id: "streams", label: "Стримы" },
  { id: "backend-logs", label: "Backend logs" },
];
