export const ADMIN_TABS = [
  { id: "operations", label: "Оперативный дэшборд", shortLabel: "Оперативка" },
  { id: "reports", label: "Журнал" },
  { id: "companies", label: "Компании" },
  { id: "operators", label: "Операторы" },
  { id: "captchas", label: "Капчи" },
  { id: "invoices", label: "Счета" },
  { id: "expenses", label: "Расходы" },
  { id: "finance", label: "Финансы" },
  { id: "payouts", label: "Выплаты" },
  { id: "users", label: "Пользователи" },
  { id: "testbench", label: "Тесты и бенчмарк", shortLabel: "Тесты" },
  { id: "training", label: "Обучение" },
  { id: "streams", label: "Стримы" },
  { id: "backend-logs", label: "Техстатус", shortLabel: "Tech" },
  { id: "prepaid", label: "Предоплата", shortLabel: "Аванс" },
  { id: "channels", label: "Каналы" },
  { id: "ai", label: "ИИ" },
];
