"""SSE connection management."""

from src.sse.manager import (
    get_connected_streams,
    get_master_operators,
    get_operator_display_modes,
    get_operator_masters,
    lock,
    pending,
    push_sse,
    push_sse_owner_and_operators,
    register_sse_connection,
    replace_sse_connections,
    set_master_operators,
    set_operator_display_mode,
    set_operator_masters,
    sse_queues,
    super_kiosk_subscriptions,
    unlink_operator_from_master,
    unregister_sse_connection,
)

__all__ = [
    "get_connected_streams",
    "get_master_operators",
    "get_operator_display_modes",
    "get_operator_masters",
    "lock",
    "pending",
    "push_sse",
    "push_sse_owner_and_operators",
    "register_sse_connection",
    "replace_sse_connections",
    "set_master_operators",
    "set_operator_display_mode",
    "set_operator_masters",
    "sse_queues",
    "super_kiosk_subscriptions",
    "unlink_operator_from_master",
    "unregister_sse_connection",
]
